<a href="https://colab.research.google.com/github/Geerford/data-science-ipynb/blob/master/Clustering/K_means.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Подключение библиотек

In [ ]:
import numpy as np
import pandas as pd
from sklearn.cluster import KMeans

Подключение gdrive

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
%cd '/content/drive/My Drive/Colab Notebooks/Data Science/Clustering'

/content/drive/My Drive/Colab Notebooks/Data Science/Clustering


Обработка данных

In [ ]:
data = pd.read_csv("k-means.csv", delimiter=',', index_col='Object')
X = data.drop('Cluster', axis=1)
y = data['Cluster']

Обучение модели. n_init - количество запуска алгоритма с разными сидами центроидов

In [ ]:
init_centroids = np.array([[11.6, 12.4], [12.13, 9.13], [1.5, 18.0]])
model = KMeans(n_clusters=3, init=init_centroids, max_iter=100, n_init=1)
model.fit(X)

KMeans(algorithm='auto', copy_x=True,
       init=array([[11.6 , 12.4 ],
       [12.13,  9.13],
       [ 1.5 , 18.  ]]),
       max_iter=100, n_clusters=3, n_init=1, n_jobs=None,
       precompute_distances='auto', random_state=None, tol=0.0001, verbose=0)

Расстояние от данных до всех центроидов

In [ ]:
print('All distances: \n{}'.format(model.fit_transform(X)))

All distances: 
[[ 1.01379376  9.26350366 12.98768648]
 [ 1.53659074  7.40354645 13.8014492 ]
 [14.70921858 18.91593244  6.31506136]
 [ 7.12000312 14.67353059 11.37013632]
 [13.44226337 13.20274593  2.80713377]
 [13.17931882 16.81703006  4.20475921]
 [11.51930746  9.76281209  5.5569776 ]
 [ 4.32370726  7.16327439  8.83628881]
 [ 5.06896878  3.28823661 12.39677377]
 [ 8.08462189  1.52069063 15.38440769]
 [ 2.94863434  6.73145601 14.82160585]
 [ 7.09655629  1.95256242 14.96930192]
 [13.30517861  5.36772764 15.33883959]
 [14.40003858 14.15317985  3.04630924]
 [ 4.62180821  7.7014609  16.81903683]]


Полученные классы всех объектов

In [ ]:
print('Labels for each object: {}'.format(model.labels_))

Labels for each object: [0 0 2 0 2 2 2 0 1 1 0 1 1 2 0]


Финальные координаты центроидов

In [ ]:
print('Centroids: \n{}'.format(model.cluster_centers_))

Centroids: 
[[14.83333333 14.        ]
 [14.5         5.75      ]
 [ 2.2        12.8       ]]
